spring:
  # redis配置；若不使用redis请删除reids依赖且删除该配置
  redis:
    timeout: ${REDIS_TIMEOUT:1500}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:1}
    jedis:
      pool:
        max-active: ${REDIS_MAX_ACTIVE:20}
        max-idle: ${REDIS_MAX_IDLE:8}
        min-idle: ${REDIS_MIN_IDLE:3}
  # 数据库配置；若不使用数据库，需删除数据库依赖且删除该配置
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:localhost:3306}/${MYSQL_DATABASE:test}?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:ENC(MsyeNprxWtUGxIuf5+R3Lw==)} #使用jasypt加密
    druid:
      initial-size: ${DATASOURCE_INITIAL_SIZE:3} #初始链接数
      min-idle: ${DATASOURCE_MIN_IDLE:3} # 最小空闲链接
      max-active: ${DATASOURCE_MAX_ACTIVE:30} # 最大链接数
      # 配置获取连接等待超时的时间
      max-wait: 30000
      # 检测空闲链接的间隔时间，检测后关闭空闲链接
      time-between-eviction-runs-millis: 30000
      # 链接的最小生存时间（空闲时间）
      min-evictable-idle-time-millis: 1800000 #最小空闲时间
      # 最大空闲时间
      max-evictable-idle-time-millis: 3600000 #最大空闲时间
      validation-query: SELECT 1
      validation-query-timeout: 10000
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      # 每个链接PSCache大小
      max-pool-prepared-statement-per-connection-size: 20
      # 监控拦截的filters,监控统计:stat,日志:log4j,防御sql注入:wall
      filters: stat,wall,slf4j
      #采集web-jdbc关联监控的数据(url,jdbc数量等)
      web-stat-filter: # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        enabled: true #是否启用StatFilter默认值true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      # StatViewServlet配置统计界面地址
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet默认值true
        reset-enable: false #允许手动清空数据
        url-pattern: /druid/* #访问地址
        # 配置其他机器可以访问该地址，否则只有localhost可以访问
        allow:
      # 方法调用监控，使用spring aop技术
      aop-patterns: com.main.*
      # 多久打印一次统计数据日志
      timeBetweenLogStatsMillis: 120000

# mybatis配置 若不使用数据库，需删除数据库依赖且删除该配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志打印，比较耗性能，不打开
pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

logging:
  config: classpath:log4j2-${LOG4J2_PROFILES:console}.xml


